content:
  - name: events
    label: Events
    path: src/events
    filename: '{fields.title}/index.md'
    type: collection
    view:
      fields: [title, date, tags]
    fields:
      - name: layout
        label: Layout
        type: string
        default: event.njk
        hidden: true
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Event Date
        type: date
        required: true
        options:
          format: yyyy-MM-dd
      - name: description
        label: Description
        type: text
      - name: featured
        label: Featured Image
        type: image
        required: true
        options:
          path: src/events/{fields.title}
          multiple:
            max: 1
      - name: images
        label: Additional Images
        type: image
        required: true
        options:
          path: .
          multiple:
            max: 20
      - name: tags
        label: Tags
        type: select
        required: true
        options:
          values: ["2nd EC", "3rd EC", "4th EC", "5th EC"]
          multiple: false
          creatable: true
      - name: content
        label: Content
        type: rich-text
        required: true
media:
  input: src/events
  output: /events