content:
  - name: events
    label: Events
    path: src/events
    filename: '{fields.date|date:YYYY-MM-DD}-{fields.title}.md'
    type: collection
    view:
      fields: [title, date, tags]
    fields:
      - name: layout
        label: Layout
        type: string
        default: event.njk
      - name: title
        label: Title
        type: string
      - name: date
        label: Event Date
        type: date
        options:
          format: YYYY-MM-DD
      - name: description
        label: Description
        type: text
      - name: featured
        label: Featured Image
        type: image
        multiple: true
      - name: images
        label: Additional Images
        type: image
        multiple: true
      - name: tags
        label: Tags
        type: string
        options:
          values: ["2nd EC", "3rd EC", "4th EC", "5th EC"]
      - name: body
        label: Event Details
        type: rich-text
media:
  input: src/contents/images
  output: /contents/images