# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: rupsaclub/rupsaclub.github.io
  branch: main
  identity_url: https://auth.decapbridge.com/sites/0ac4752d-b3e3-43ef-ad2e-61ba8a05d93b
  gateway_url: https://gateway.decapbridge.com

# Quickly see who did what (optional)
commit_messages:
  create: Create {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
  update: Update {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
  delete: Delete {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
  uploadMedia: Upload "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
  deleteMedia: Delete "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
  openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://rupsa.club

media_folder: "src/contents/images/uploads"
public_folder: "/contents/images/uploads"

collections:
  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "src/events"
    create: true
    slug: "{{fields.committee}}/{{slug}}"
    extension: "md"
    format: "frontmatter"
    path: "{{slug}}/index"
    nested:
      depth: 100
      summary: "{{title}}"
    fields:
      - name: "layout"
        label: "Layout"
        widget: "hidden"
        default: "event.njk"
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "date"
        label: "Date"
        widget: "datetime"
      - name: "description"
        label: "Description"
        widget: "text"
        required: false
      - name: "featured"
        label: "Featured Image(s)"
        widget: "list"
        required: false
        field:
          label: "Image"
          name: "image"
          widget: "image"
      - name: "images"
        label: "Gallery Images"
        widget: "list"
        required: false
        field:
          label: "Image"
          name: "image"
          widget: "image"
      - name: "committee"
        label: "Committee Year"
        widget: "select"
        required: true
        options:
          - label: "2nd EC"
            value: "2ndEC"
          - label: "3rd EC"
            value: "3rdEC"
          - label: "4th EC"
            value: "4thEC"
        default: "4thEC"
      - name: "tags"
        label: "Tags"
        widget: "select"
        required: false
        multiple: true
        options:
          - label: "2nd EC"
            value: "2nd EC"
          - label: "3rd EC"
            value: "3rd EC"
          - label: "4th EC"
            value: "4th EC"
        default: ["4th EC"]
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "committee"
    label: "Committees"
    folder: "src/committee"
    create: true
    slug: "{{slug}}"
    # Remove or fix nested config if folders don't exist
    # nested:
    #   depth: 1
    #   summary: "{{title}}"
    fields:
      - { name: "title", label: "Committee Year", widget: "string" }
      - {
          name: "body",
          label: "Description / Details",
          widget: "markdown",
          required: false,
        }

  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "src/about.njk"
        fields:
          - {
              name: "title",
              label: "Title",
              widget: "string",
              default: "About",
            }
          - { name: "body", label: "Body", widget: "markdown" }
      - label: "Advisory Committee"
        name: "advisory"
        file: "src/advisory.njk"
        fields:
          - {
              name: "title",
              label: "Title",
              widget: "string",
              default: "Advisory Committee",
            }
          - { name: "body", label: "Body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "src/contact.njk"
        fields:
          - {
              name: "title",
              label: "Title",
              widget: "string",
              default: "Contact",
            }
          - { name: "body", label: "Body", widget: "markdown" }
      - label: "FAQs"
        name: "faqs"
        file: "src/faqs.njk"
        fields:
          - { name: "title", label: "Title", widget: "string", default: "FAQs" }
          - { name: "body", label: "Body", widget: "markdown" }