# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: rupsaclub/rupsaclub.github.io
  branch: main
  identity_url: https://auth.decapbridge.com/sites/0ac4752d-b3e3-43ef-ad2e-61ba8a05d93b
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://rupsa.club

media_folder: "src/contents/images/uploads"
public_folder: "/contents/images/uploads"


collections:
  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "src/events"
    create: true
    slug: "{{slug}}"
    nested:
      depth: 2
      summary: "{{title}}"
    fields:
      - {
          name: "layout",
          label: "Layout",
          widget: "hidden",
          default: "event.njk",
        }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - {
          name: "description",
          label: "Description",
          widget: "text",
          required: false,
        }
      - label: "Featured Image(s)"
        name: "featured"
        widget: "list"
        field: { label: "Image", name: "image", widget: "image" }
      - label: "Gallery Images"
        name: "images"
        widget: "list"
        field: { label: "Image", name: "image", widget: "image" }
      - label: "Tags / Committee Year"
        name: "tags"
        widget: "select"
        options:
          - { label: "2nd EC", value: "2nd EC" }
          - { label: "3rd EC", value: "3rd EC" }
          - { label: "4th EC", value: "4th EC" }
        default: "4th EC"
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "committee"
    label: "Committees"
    folder: "src/committee"
    create: true
    slug: "{{slug}}"
    nested:
      depth: 1
      summary: "{{title}}"
    fields:
      - { name: "title", label: "Committee Year", widget: "string" }
      - {
          name: "body",
          label: "Description / Details",
          widget: "markdown",
          required: false,
        }

  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "src/about.njk"
        fields:
          - {
              name: "title",
              label: "Title",
              widget: "string",
              default: "About",
            }
          - { name: "body", label: "Body", widget: "markdown" }
      - label: "Advisory Committee"
        name: "advisory"
        file: "src/advisory.njk"
        fields:
          - {
              name: "title",
              label: "Title",
              widget: "string",
              default: "Advisory Committee",
            }
          - { name: "body", label: "Body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "src/contact.njk"
        fields:
          - {
              name: "title",
              label: "Title",
              widget: "string",
              default: "Contact",
            }
          - { name: "body", label: "Body", widget: "markdown" }
      - label: "FAQs"
        name: "faqs"
        file: "src/faqs.njk"
        fields:
          - { name: "title", label: "Title", widget: "string", default: "FAQs" }
          - { name: "body", label: "Body", widget: "markdown" }
